// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upfvwlqxaaunzpgejhyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZnZ3bHF4YWF1bnpwZ2VqaHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzODEyOTQsImV4cCI6MjA1NDk1NzI5NH0.r0My6pZfp4vajWgXaCA5nAbtpJ671Vwwv5x38wtlNgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);